#ifndef STATUS_CODE
#define STATUS_CODE

enum e_status_code
{
	STATUS_OK = 200,
	STATUS_CREATED = 201,
	STATUS_NO_CONTENT = 204,
	STATUS_MOVED = 301,
	STATUS_BAD_REQUEST = 400,
	STATUS_FORBIDDEN = 403,
	STATUS_NOT_FOUND = 404,
	STATUS_NOT_ALLOWED = 405,
	STATUS_REQUEST_TIMEOUT = 408,
	STATUS_CONFLICT = 409,
	STATUS_LENGTH_REQUIRED = 411,
	STATUS_TOO_LARGE = 413,
	STATUS_URI_TOO_LONG = 414,
	STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
	STATUS_INTERNAL_ERR = 500,
	STATUS_NOT_IMPLEMENTED = 501,
	STATUS_BAD_GATEWAY = 502,
	STATUS_GATEWAY_TIMEOUT = 504,
	STATUS_VERSION_NOT_SUPPORTED = 505,
};

#endif
